POST http://localhost:8080/costs
Content-Type: application/json

{"user":{"id":2,"name":"Дарья"},"month":"2023-01-21","category":{"id":1,"label":"Аренда квартиры"},"sum":2000}

###
GET http://localhost:8080/costs
Accept: application/json

###
